version: "3"

services:
  fastapi_app:
    image: fastapi-app
    ports:
      - "81:81"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: fastapi_db