version: "3"

services:
  fastapi_app:
    build: .
    volumes:
      - .:/app
    image: fastapi-app
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "81:8001"
    depends_on:
      - db

  db:
    image: postgres:14.8-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: fastapi_db