version: "3"

services:
  fastapi_app:
    image: fastapi-app
    ports:
      - "81:81"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: m89_fastapi_blog
      POSTGRES_USER: m89_fastapi_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: fastapi_db