"""remove role FK

Revision ID: 187def0f98be
Revises: a9d8fd90c08a
Create Date: 2023-03-11 19:59:37.107419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187def0f98be'
down_revision = 'a9d8fd90c08a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_id_fkey', 'users', 'role', ['role_id'], ['role_id'], ondelete='RESTRICT')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
