"""delete status

Revision ID: cd72f0de2017
Revises: 73d53b4b2451
Create Date: 2023-03-11 19:53:00.567197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd72f0de2017'
down_revision = '73d53b4b2451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint('comments_status_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'status_id')
    op.add_column('posts', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint('posts_status_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_status_id_fkey', 'posts', 'status', ['status_id'], ['status_id'], ondelete='RESTRICT')
    op.drop_column('posts', 'status')
    op.add_column('comments', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_status_id_fkey', 'comments', 'status', ['status_id'], ['status_id'])
    op.drop_column('comments', 'status')
    # ### end Alembic commands ###
