"""01_ add table user request

Revision ID: 52692854b244
Revises: 
Create Date: 2023-03-16 16:36:59.969163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52692854b244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_request',
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_request')
    # ### end Alembic commands ###
