"""03_ add unique together user id and request name

Revision ID: 68d2e6dbad01
Revises: e30df439cb19
Create Date: 2023-03-16 17:05:50.591107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d2e6dbad01'
down_revision = 'e30df439cb19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_request', 'user_request', ['user_id', 'request_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_request', 'user_request', type_='unique')
    # ### end Alembic commands ###
