"""04_ update request user

Revision ID: 90e77d4175e9
Revises: 68d2e6dbad01
Create Date: 2023-03-16 19:15:42.752552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e77d4175e9'
down_revision = '68d2e6dbad01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request', sa.Column('status', sa.String(), nullable=False))
    op.add_column('user_request', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_request', sa.Column('last_update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_request', 'last_update')
    op.drop_column('user_request', 'created_at')
    op.drop_column('user_request', 'status')
    # ### end Alembic commands ###
