"""05 unique user request

Revision ID: d1f49176f978
Revises: 
Create Date: 2023-03-17 17:14:18.994942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f49176f978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_request', 'user_request', type_='unique')
    op.create_unique_constraint('unique_request', 'user_request', ['user_id', 'request_name', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_request', 'user_request', type_='unique')
    op.create_unique_constraint('unique_request', 'user_request', ['user_id', 'request_name'])
    # ### end Alembic commands ###
