"""08 add ContactUs table

Revision ID: deca059d8741
Revises: b3aec22b4194
Create Date: 2023-03-25 21:33:15.001633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deca059d8741'
down_revision = 'b3aec22b4194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('name', sa.String(), nullable=False))
    op.add_column('contact_us', sa.Column('content', sa.String(), nullable=False))
    op.add_column('contact_us', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('contact_us_user_id_fkey', 'contact_us', type_='foreignkey')
    op.drop_column('contact_us', 'user_id')
    op.drop_column('contact_us', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contact_us', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('contact_us_user_id_fkey', 'contact_us', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('contact_us', 'created_at')
    op.drop_column('contact_us', 'content')
    op.drop_column('contact_us', 'name')
    # ### end Alembic commands ###
