"""02_ add request_name to table user request

Revision ID: e30df439cb19
Revises: 52692854b244
Create Date: 2023-03-16 16:40:52.799887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30df439cb19'
down_revision = '52692854b244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_request', sa.Column('request_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_request', 'request_name')
    # ### end Alembic commands ###
